
development:
  adapter: mysql2
  database: moviesengine_test
  username: root
  password: root
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  
test:
  adapter: mysql2
  database: moviesengine_production
  username: root
  password: root
  host: 127.0.0.1

staging:
  adapter: mysql2
  database: moviesengine_staging
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: moviesengine_production
  username: root
  password: root
  host: 127.0.0.1