Site.find_or_create_by(:name => 'Watch Online Movies', :url => 'http://www.watchonlinemovies.com.pk')
Site.find_or_create_by(:name => 'Fmovise.se', :url => 'https://fmovies.se/movies')
Site.find_or_create_by(:name => 'onlinemoviescinema', :url => 'http://onlinemoviescinema.cc')
Site.find_or_create_by(:name => 'm4free', :url => 'http://m4ufree.com')
Site.find_or_create_by(:name => '1movie.onlile', :url => 'https://1movies.online')
Site.find_or_create_by(:name => '1movie.onlile Seasons', :url => 'https://1movies.online/latest/series')
Site.find_or_create_by(:name => 'Watcheng Movies', :url => 'https://watcheng.com')
Site.find_or_create_by(:name => 'TV-Daramas Pakistan', :url => 'http://www.tv-dramas.pk')
Site.find_or_create_by(:name => 'FMovies TV Serials', :url => 'https://fmovies.se/tv-series')

